# Generated by Django 3.0 on 2019-12-20 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('mi_account', models.CharField(max_length=8)),
                ('employee_mi_loc', models.CharField(max_length=4)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_title', models.CharField(blank=True, max_length=40, null=True)),
                ('employee_dept', models.CharField(blank=True, max_length=25, null=True)),
                ('job_code', models.CharField(max_length=5)),
                ('job_status', models.CharField(blank=True, max_length=5, null=True)),
                ('job_position', models.CharField(blank=True, max_length=30, null=True)),
                ('supervisor_id', models.CharField(blank=True, max_length=6, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_updated_date', models.DateField(default=datetime.date.today, editable=False)),
            ],
            options={
                'ordering': ['employee_mi_loc'],
            },
        ),
    ]
