# Generated by Django 3.0 on 2019-12-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ship_to_account_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('corp', models.CharField(max_length=4)),
                ('territory', models.CharField(max_length=6)),
                ('territory_description', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=4)),
                ('division', models.CharField(max_length=4)),
                ('mi_loc', models.CharField(max_length=4)),
                ('location_description', models.CharField(max_length=100)),
                ('customer_no', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['ship_to_account_number'],
                'unique_together': {('customer_no', 'mi_loc')},
            },
        ),
    ]
